# https://docs.snapcraft.io/snapcraft-yaml-reference/4276
name: iturhfprop # you probably want to 'snapcraft register <name>'
version: '0.1+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: HF Propagation Prediction # 79 char long summary
description: |
  HF Propagation Prediction in accordance with ITU-R P.533-13.

grade: stable
confinement: strict

apps:
    iturhfprop:
        command: usr/bin/ITURHFProp
        plugs: [home]

parts:
  iturhfprop:
    source: https://github.com/onetablespoon/ITU-R-HF.git
    plugin: make
    makefile: Makefile
    make-parameters:
        - 'prefix=/usr/'
        - '-C'
        - '/home/jwatson/github/itu-snap/parts/iturhfprop/build/Linux/'
